### ISSUE TITLE
💫 Refactor configure / login to graph API

### ISSUE THREAD

**Issue by leny** [becodeorg/cli#24]
When the graphAPI coming to production, it will be better to hook the cli to the graph API.

The cli will become a _client_, and will not need to be a _second_ source of data.

The primary goal is to allow becode users to log into the API from the cli, then we will be able to replicate some _mybecode_ actions from the cli (we already have the needs for some coaches).

### TODO

- [ ] Remove the `configure` command
- [ ] Implement the following commands:
  - [ ] `register` (use the graph API `registerWithBasic` mutation)
  - [ ] `login` (use the graph API `loginWithBasic` mutation)
  - [ ] `logout` (use the graph API `revoke` mutation)
- [ ] save the token in `~/.becode.cli.json` file
- [ ] refactor `open` command to use the graph API data
